### ISSUE TITLE
How to sort data or get a list so I can perform a click through adapter? 

### ISSUE THREAD

**Issue by emailsubjekt** [PatilShreyas/FirebaseRecyclerPagination#10]
Can you please help me, I just came from here https://firebaseopensource.com/projects/patilshreyas/firebaserecyclerpagination/app/readme.md/ 
It works amazingly, however, there are no onClick, onLongClick methods in there for when a user presses on the item. I have made it through adapter but I used a list in the old one. How do I get a list of data here with pagination so that I can search through it and how can I sort this data? I have read something about using a parser but can't find an example anywhere on how to do it?

**Comment by PatilShreyas** [comment]
This adapter is now officially part of FirebaseUI-Android repository here: https://github.com/firebase/FirebaseUI-Android.

I would recommend you to use this library as this is deprecated.

**Comment by emailsubjekt** [comment]
Dude, I asked a bunch of questions you just referred me to a website that also doesn't have answers, I already looked through that example and it doesn't contain the answers. However I solved it anyway while you were busy typing 2 sentences so I don't need it anymore. Thank you for answering the whole 2 sentences anyway.

**Comment by emailsubjekt** [comment]
I still can't solve how the parser works, I parse the data but then I get for example 3 items that I was looking for but each item has 10 copies of itself, basically the adapter is filling up to the number of all products just re-positioning the 3 items I was looking for over the span of the entire list, making each item take up a third, lol. At least answer me how the parser works if you're not gonna talk about the rest. I can't find it anywhere on the internet!

**Comment by PatilShreyas** [comment]
@emailsubjekt that `SnapshotParser` you're talking about is developed by official Firebase SDK. 

If you want to implement `onClick()` and other methods on `View` then override `onBindViewHolder()` method of paging adapter of official library class. (I've given link above). Then you can access each `ViewHolder` of child.

**Comment by emailsubjekt** [comment]
I've done that. I am asking about the parsing of data, I want to make search work. 

Here I can return dataModel, I've tried 'if contains 'string'' and I get the right results out, however, I get 10 copies of each right result, meaning duplicates! Is there an example of how to parse correctly? Can you please help?

  DatabasePagingOptions<AdminDataModel> options = new DatabasePagingOptions.Builder<AdminDataModel>()
                .setLifecycleOwner(this)
                .setQuery(mDatabase, config, new SnapshotParser<AdminDataModel>() {
                            @NonNull
                            @Override
                            public DataModel parseSnapshot(@NonNull DataSnapshot dataSnapshot) {

**Comment by PatilShreyas** [comment]
As per official Firebase, Real-time database does not supports such complex operations. For this, you will have to implement your own adapter or you'll have to migrate your database to Cloud Firestore - new powerful database by Firebase.

Official documentation on searching is available here:
https://firebase.google.com/docs/firestore/solutions/search

**Comment by emailsubjekt** [comment]
I understand SnapshotParser is developed by official Firebase SDK, however there isn't an example of how to use it anywhere. You're the closest person to the subject that probably has the knowledge that's why I'm asking you. I found parser in the common folder of the Firebase UI example you sent, however it's not an example of an app. It's just instructions for migration to AndroidX and contains stuff like 

package com.firebase.ui.common;

import androidx.annotation.NonNull;

/**
 * Common interface for snapshot parsers.
 *
 * @param <S> snapshot type.
 * @param <T> parsed object type.
 */
public interface BaseSnapshotParser<S, T> {

    /**
     * This method parses the Snapshot into the requested type.
     *
     * @param snapshot the Snapshot to extract the model from
     * @return the model extracted from the DataSnapshot
     */
    @NonNull
    T parseSnapshot(@NonNull S snapshot);

}

There is literally no example in there that relates to parsing stuff by means of search. 

Can you please help, how do I search paginated data?

**Comment by PatilShreyas** [comment]
If you need to customize how your model class is parsed, you can use a custom `SnapshotParser`. It's not used to sort out required data. For that case, you'll have to implement your own custom adapter. Or use powerful database as Cloud Firestore. It'll really help you out as it supports complex queries.

**Comment by emailsubjekt** [comment]
What do you mean doesn't support? Why do they have a parser implemented then for us to use? They just removed that from the official pagination page, it was there yesterday as an example. Now it isn't there anymore, what kind of a game is this?

**Comment by emailsubjekt** [comment]
Yes, how do I use a custom SnapshotParser?

**Comment by emailsubjekt** [comment]
I don't want to use Firestore, I've built the whole system on Firebase RealtimeDatabase, moving to Firestore would take months. I have my own adapter, however loading data takes 5-7 seconds. Loading data with pagination, with this example loads it in half a second! Therefore I want to use this. Also you say it does not sort out data, but I've sorted it out, it just gives me duplicates of it! I want to get rid of those duplicates. There must be an example of SnapshotParser being used right?

**Comment by PatilShreyas** [comment]
It's available [here](https://github.com/firebase/FirebaseUI-Android/tree/master/database) already. But whatever you want to implement you can't get it by using SnapshotParser. It's used for parsing model class using modifications.

**Comment by emailsubjekt** [comment]
Yes! This what you sent: 
"
If you need to customize how your model class is parsed, you can use a custom SnapshotParser:

...setQuery(..., new SnapshotParser<Chat>() {
    @NonNull
    @Override
    public Chat parseSnapshot(@NonNull DataSnapshot snapshot) {
        return ...;
    }
});
"


Why isn't there a whole example here? Do you have possibly an example of how to use this. Oh I understand, what you're saying I can't limit the number of loaded items because it's just parsing model class using modification and since I don't really know which ones the search results spewed out I can't really limit what it's showing? Can't I just somehow tell it to remove all the duplicates it put up?

**Comment by PatilShreyas** [comment]
I already told you to make your custom RecyclerAdapter. There you'll need to maintain customised data in your list and then you can show that list.

**Comment by emailsubjekt** [comment]
Just to clarify, I'm using the code above, taking the snapshot, taking out the DataModel from the snapshot, looking at the String inside, comparing it with the string I'm looking for and if it matches I return it at the end of the method. This gives me correct search results, however each search results is duplicated to the amount of 1/x of the original list if there are x results. I want to solve that somehow. You're telling me I can't remove those duplicates? But there must be a way.

**Comment by emailsubjekt** [comment]
I don't know how to make a custom adapter using these 

    //Initialize PagedList Configuration
        PagedList.Config config = new PagedList.Config.Builder()
                .setEnablePlaceholders(false)
                .setPrefetchDistance(5)
                .setPageSize(10)
                .build();


      DatabasePagingOptions<DataModel> options = new DatabasePagingOptions.Builder<DataModel>()
               .setLifecycleOwner(this)
                .setQuery(mDatabase, config, DataModel.class)
                .build();

Is there an example somewhere?

**Comment by emailsubjekt** [comment]
I thought the parser would be the only way I could get the data into an array list then I figured out I could use it without the arraylist, just parsing datamodels directly, now you tell me I can't, I've managed to get the list through onBind for the adapter where I use it for onClick of the item and it works, but how do I filter that data if the recyclerView is listening only to these commands from the pagination cycle? I am so lost right now.

**Comment by PatilShreyas** [comment]
For this, you'll have to learn basics of RecyclerView and Adapter in AndroidX. Then you'll get idea of that.

**Comment by emailsubjekt** [comment]
Where can I learn that, there doesn't seem to be a comprehensive way to learn this other than constantly downloading new examples that work.

Also I've found these examples 

https://stackoverflow.com/questions/50596637/android-reading-a-value-from-a-child-with-firebaseui
    FirebaseRecyclerOptions<User> options = new FirebaseRecyclerOptions.Builder<User>()
                .setQuery(query, new SnapshotParser<User>() {
                    @NonNull
                    @Override
                    public User parseSnapshot(@NonNull DataSnapshot snapshot) {
                        String Name = snapshot.child(App_Constants.INFO_COLUMN).child(App_Constants.NAME_COLUMN).getValue().toString();
                        String State = snapshot.child(App_Constants.INFO_COLUMN).child(App_Constants.STATE_COLUMN).getValue().toString();
                        String Image = snapshot.child(App_Constants.INFO_COLUMN).child(App_Constants.IMAGE_COLUMN).getValue().toString();
                        User user = new User(Name,State,Image);

                        return user;
                    }
                }).build();

---------------------------
https://stackoom.com/question/3mDmC/RecyclerView-for-group-chat%E6%B4%BB%E5%8A%A8%E6%9C%AA%E6%98%BE%E7%A4%BA%E5%9C%A8Android-Studio%E4%B8%AD%E7%9A%84FirebaseUI%E4%B8%AD

        //FirebaseRecyclerAdapter binds query to a RecycleView.  When data is added, removed or changed these updates are automatically applied to UI in real time.
        options = new FirebaseRecyclerOptions.Builder<ChatMessage>()
                .setLifecycleOwner(this)
                .setQuery(query, new SnapshotParser<ChatMessage>(){
                @NonNull
                @Override
                public ChatMessage parseSnapshot(@NonNull DataSnapshot snapshot) { //Needed to customize how ChatMessage class is parsed
                    Log.v("TAG", "in parseSnapshot");
                    return new ChatMessage(snapshot.child("Body").getValue().toString(), snapshot.child("Username").getValue().toString());
                }
            }).build();


Obviously they're parsing data, I'm guessing they're just showing all the data at that location instead of parsing it locally or taking bits of the DataModel data instead of all of it? I already have a whole adapter built with search and the old way of downloading but I wanted to use pagination with search. I have found several examples, some of them seem to utilize weird ways of going about this, however none work. The only ones that work are the ones that have scrollListeners on RecyclerView and measure items to display the next 20 for example after user scrolls the first 20. Please I need examples to finish this, can you send me some examples?

**Comment by PatilShreyas** [comment]
You can learn it online or refer any official android repositories. If any
problem occurs then stackoverflow would help you better.

**Comment by emailsubjekt** [comment]
Come on dude, you're telling me you don't know of any examples that have pagination and search implemented? I need help here!

**Comment by PatilShreyas** [comment]
Actually I also haven't implemented it practically. And this is not right
platform to discuss it. You can get better help on stackoverflow. If you
ask questions on stackoverflow you can get help from experts.

**Comment by emailsubjekt** [comment]
That's all you needed to say, I thought you've already done it or know how. Well now I'm even more in the shi**er. I gotta go look on for solutions, lol. Good luck mate!
