### ISSUE TITLE
Problem with Query

### ISSUE THREAD

**Issue by aruphazarika** [PatilShreyas/FirebaseRecyclerPagination#2]
I use a query by replacing 'mdatabase', when scrolling down  it shows " can't call equal to () or start at() multiple times. I am querying data with equal to. Thanks.

**Comment by PatilShreyas** [comment]
Hi @aruphazarika, Till now, this adapter doesn't supports the use of queries with `equalTo()`, `startAt()`, `endAt()` due to internal reasons.
Thanks for filling!

**Comment by aruphazarika** [comment]
Ohh ! Will you add this support in future? Thanks

**Comment by PatilShreyas** [comment]
@aruphazarika Yes. I will try to solve it. Thanks

**Comment by PatilShreyas** [comment]
@aruphazarika Internally, we modified the `Query` for pagination. So, we can not add this support because of Firebase Database API not having methods for such manipulation so that we can add it.
Thanks for filing this issue.
I'm Closing this.
