### ISSUE TITLE
Using orderByChild gives infinite scrolling

### ISSUE THREAD

**Issue by ShahrearBinAmin** [PatilShreyas/FirebaseRecyclerPagination#4]
In query, I'm using orderByChild but It shows infinite scrolling. Except for first item, other items are appending at the end of recyclerview.

**Comment by PatilShreyas** [comment]
Hi @ShahrearBinAmin, Sorry for the super late reply but internally it's too much complex thing for firebase real-time database to handle this. I'll suggest you migrate the database to firestore. It supports such complex things. Thank you for your time,
