### ISSUE TITLE
Problem with refresh

### ISSUE THREAD

**Issue by KornGit** [PatilShreyas/FirebaseRecyclerPagination#6]
Hi again.
I noticed that when I refresh my layout SwipeRefreshLayout refreshes twice and loading icon shows twice however second time in very very short.

Refresh goes from states
LOADING MORE -> LOADED -> LOADING MORE -> FINISHED

```
@Override
            protected void onLoadingStateChanged(@NonNull LoadingState state) {
                switch (state) {
                    case LOADING_INITIAL:
                    case LOADING_MORE:
                        Log.d(TAG, "LOADING MORE");
                        mSwipeRefreshLayout.setRefreshing(true);
                        break;

                    case LOADED:
                        Log.d(TAG, "LOADED");
                        mSwipeRefreshLayout.setRefreshing(false);
                        break;

                    case FINISHED:
                        Log.d(TAG, "FINISHED");
                        mSwipeRefreshLayout.setRefreshing(false);
                        break;

                    case ERROR:
                        Log.d(TAG, "ERROR");
                        retry();
                        break;
                }
            }
```
Any reason why it doesn't stop after LOADED state and goes again to LOADING_MORE?

**Comment by PatilShreyas** [comment]
Hi @KornGit, Actually internally whenever the query is finished loading. Its state is updated. It tries to load more but its terminated due to pagination. So it has happened. This isn't a major issue. Thank you for your time and sorry for the late reply.
